#!/usr/bin/lua

--pasar a modo biblioteca de usb4all.request


local socket = require("socket")

--local host, port = "192.168.10.1", 2009
local host, port = "localhost", 2009

local client = assert(socket.connect(host, port))
client:settimeout(nil) --blocking
--client:settimeout(1)

local function send(s)
    print("sending", s)
    client:send(s.."\n")
    local ret = client:receive()
    print("ret:", ret)
    return ret
end
send("LIST")
send("CALL display reset")
send("LIST")
local ret = send("OPEN display")
print("el handler del display es " .. ret)
send("CALL display iniciar")
while true do
-- TODO mandar un resetear
    send("CALL display iniciar")
    send("CALL display borrar")
    send("CALL display escribir TESTING_DISPOSITIVO_RECARGA_V_01")
    socket.sleep(2)
    send("CALL display escribir Prendo_el_backlight_____________")
    send("CALL display prender_bkl")
    send("CALL display escribir Voy_a_intentar_agendar_mensaje__")
    socket.sleep(2)
    send("CALL display agendar_msg Mensaje_1_agendado_no_ciclico___ 0 0")
    send("CALL display agendar_msg Mensaje_2_agendado_no_ciclico___ 0 0")
    send("CALL display agendar_msg Mensaje_3_agendado_no_ciclico___ 0 0")
    send("CALL display agendar_msg Mensaje_4_agendado_no_ciclico___ 0 1")
    socket.sleep(10)
    send("CALL display escribir Cambio_tiempo_entre_mensajes_max")
    socket.sleep(2)
    send("CALL display set_ticks 255")
    send("CALL display agendar_msg Mensaje_1_agendado_no_ciclico___ 0 0")
    send("CALL display agendar_msg Mensaje_2_agendado_no_ciclico___ 0 0")
    send("CALL display agendar_msg Mensaje_3_agendado_no_ciclico___ 0 0")
    send("CALL display agendar_msg Mensaje_4_agendado_no_ciclico___ 0 1")
    socket.sleep(20)
    send("CALL display escribir Cambio_tiempo_entre_mensajes_min")
    socket.sleep(2)
    send("CALL display set_ticks 10")
    send("CALL display agendar_msg Mensaje_1_agendado_no_ciclico___ 0 0")
    send("CALL display agendar_msg Mensaje_2_agendado_no_ciclico___ 0 0")
    send("CALL display agendar_msg Mensaje_3_agendado_no_ciclico___ 0 0")
    send("CALL display agendar_msg Mensaje_4_agendado_no_ciclico___ 0 1")
    socket.sleep(5)
    send("CALL display escribir Apagar__el_backlight_____________")
    send("CALL display apagar_bkl")
    socket.sleep(2)
    send("CALL display escribir Voy_a_intentar_agendar_msg__")
    socket.sleep(2)
    send("CALL display escribir en_paralelo_test_leds_y_buzzer__")
    socket.sleep(2)
    send("CALL display set_ticks 55")
    send("CALL display agendar_msg Mensaje_1_agendado_ciclico______ 1 0")
    send("CALL display agendar_msg Mensaje_2_agendado_ciclico______ 1 0")
    send("CALL display agendar_msg Mensaje_3_agendado_ciclico______ 1 0")
    send("CALL display agendar_msg Mensaje_4_agendado_ciclico______ 1 1")
    socket.sleep(5)
    send("CALL display agendar_msg Mensaje_5_agendado_ciclico______ 1 0")
    send("CALL display agendar_msg Mensaje_6_agendado_ciclico______ 1 0")
    send("CALL display agendar_msg Mensaje_7_agendado_ciclico______ 1 0")
    send("CALL display agendar_msg Mensaje_8_agendado_ciclico______ 1 1")
    send("CALL leds prender 1")
    send("CALL leds prender 2")
    send("CALL leds prender 3")
    socket.sleep(2)
    send("CALL leds apagar 1")
    send("CALL leds apagar 2")
    send("CALL leds apagar 3")
    socket.sleep(2)
    send("CALL leds blink 50 55 1")
    send("CALL leds blink 50 55 2")
    send("CALL leds blink 50 55 3")
    send("CALL buzzer buzzer_triple 10 5 10")
    socket.sleep(50)
    send("CALL display escribir buzzer_triple_10_5_10___________")
    send("CALL buzzer buzzer_triple 10 5 10")
    socket.sleep(2)
    send("CALL display escribir buzzer_corto_____5______________")
    send("CALL buzzer buzzer_corto 5 ")
    send("CALL leds apagar 1")
    send("CALL leds apagar 2")
    send("CALL leds apagar 3")
    socket.sleep(2)
    send("CALL display escribir blink_del_led_amarillo__________")
    send("CALL leds blink 10 255 1")
    socket.sleep(2)
    send("CALL display escribir blink_del_led_verde_____________")
    send("CALL leds blink 10 255 2")
    socket.sleep(2)
    send("CALL display escribir blink_del_led_rojo______________")
    send("CALL leds blink 10 255 3")
    socket.sleep(2)
end
